
import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ismael Martín Ramírez
 * [imartinr01@informatica.iesvalledeljerteplasencia.es]
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCajaNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCajaCajaApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCajaCajaDni = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Mincho", 0, 24)); // NOI18N
        jLabel1.setText("FORMULARIO");

        jTextFieldCajaNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCajaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCajaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCajaNombreMouseClicked(evt);
            }
        });
        jTextFieldCajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCajaNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");

        jButtonGuardar.setBackground(java.awt.Color.gray);
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Apellido");

        jTextFieldCajaCajaApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCajaCajaApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCajaCajaApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCajaCajaApellidoMouseClicked(evt);
            }
        });
        jTextFieldCajaCajaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCajaCajaApellidoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DNI");

        jTextFieldCajaCajaDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCajaCajaDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCajaCajaDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCajaCajaDniMouseClicked(evt);
            }
        });
        jTextFieldCajaCajaDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCajaCajaDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22)
                                .addComponent(jTextFieldCajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCajaCajaDni, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCajaCajaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCajaCajaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCajaCajaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

        Empleado empleado = new Empleado(jTextFieldCajaNombre.getText(), jTextFieldCajaCajaApellido.getText(), jTextFieldCajaCajaDni.getText());

        flujoEscritura(empleado);

        jButtonGuardar.setBackground(Color.yellow);
        jButtonGuardar.setText("¡GUARDADO!");


    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldCajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCajaNombreActionPerformed
        jButtonGuardar.setBackground(Color.GRAY);
    }//GEN-LAST:event_jTextFieldCajaNombreActionPerformed

    private void jTextFieldCajaCajaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCajaCajaApellidoActionPerformed
        jButtonGuardar.setBackground(Color.GRAY);
    }//GEN-LAST:event_jTextFieldCajaCajaApellidoActionPerformed

    private void jTextFieldCajaCajaDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCajaCajaDniActionPerformed
        jButtonGuardar.setBackground(Color.GRAY);
    }//GEN-LAST:event_jTextFieldCajaCajaDniActionPerformed

    private void jTextFieldCajaNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCajaNombreMouseClicked
        jButtonGuardar.setBackground(Color.GRAY);
        jButtonGuardar.setText("GUARDAR");

    }//GEN-LAST:event_jTextFieldCajaNombreMouseClicked

    private void jTextFieldCajaCajaApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCajaCajaApellidoMouseClicked
        jButtonGuardar.setBackground(Color.GRAY);
        jButtonGuardar.setText("GUARDAR");

    }//GEN-LAST:event_jTextFieldCajaCajaApellidoMouseClicked

    private void jTextFieldCajaCajaDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCajaCajaDniMouseClicked
        jButtonGuardar.setBackground(Color.GRAY);
        jButtonGuardar.setText("GUARDAR");


    }//GEN-LAST:event_jTextFieldCajaCajaDniMouseClicked
    public static void flujoEscritura(Empleado empleado) {

        FileWriter fw = null;
        PrintWriter pw = null;
        try {
            fw = new FileWriter("Formulario.txt", true);
            pw = new PrintWriter(fw);
            pw.println("************");
            pw.println("Nombre: " + empleado.getNombre());
            pw.println("Apellido: " + empleado.getApellido());
            pw.println("DNI: " + empleado.getDni());
            pw.println("************");

        } catch (IOException ex) {
            System.out.println("Error al crear el fichero en su fase inicial");
            System.out.println(ex.getMessage());
        } finally {
            if (pw != null) {
                pw.close();
            }
            if (fw != null) {
                try {
                    fw.close();
                } catch (IOException ex) {
                    System.out.println("Error al cerrar el fichero en su fase inicial");
                    System.out.println(ex.getMessage());
                }
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldCajaCajaApellido;
    private javax.swing.JTextField jTextFieldCajaCajaDni;
    private javax.swing.JTextField jTextFieldCajaNombre;
    // End of variables declaration//GEN-END:variables
}
